name: Checking Inputs and Parameters
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose the environment to deploy'
        required: true
        default: dev
        type: choice
        options:
        - dev
        - test
        - prod
      artifact_tag:
        description: 'Choose the tag to deploy'
        required: true
        type: string  # Explicitly add type

jobs:
  inputs-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Print Inputs
        run: |
          echo "Deploying ${{ github.event.inputs.artifact_tag || 'latest' }} to ${{ github.event.inputs.environment }}"
          echo "Or using inputs.*: ${{ inputs.artifact_tag }} to ${{ inputs.environment }}"
