name: Testing Evn variable
on: workflow_dispatch
env:
  APP_NAME: "dev"
jobs:
  EnvCheck:
    runs-on: ubuntu-latest
    env:
      APP_NAME: "test"
    steps:
      - name: check Evn
        env:
          APP_NAME: "Prod"
        run: echo "Connnecting to $APP_NAME"
