name: Testing Evn variable
on: push
env:
  APP_NAME: "dev"
jobs:
  EnvCheck:
    runs-on: ubuntu-latest
    env:
      APP_NAME: "test"
    steps:
      - name: check Evn
        run: echo "Connnecting to $APP_NAME"
