name: Running Hello World
on: workflow_dispatch
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
    - name: Hello step
      run: |
        echo "Hello World Step1"
        echo "How are you welcome to Github Actions"
    - name: second job
      run: |
        echo "Second Step"
        echo "job"
