name: checking the if condition
on: 
  push:
    branches: 
      - main
      - develop
jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Run if branch is main
        if: github.ref_name == 'main'
        run: echo "Running if branch is main."
      -  name: run normal
         run: echo "running without condition." 
  
