name: Mulitple jobs
on: workflow_dispatch
jobs:
  checkout-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: print the html
        run: cat index.html
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build step
        run: |
            echo "Checkouting the code from github"
            cat index.html
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Test step
        run: echo "Testing the code"
  Deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Deploying step
        run: echo "Deploying"
