name: Mulitple jobs
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build step
        run: echo "Checkouting the code from github"
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test step
        run: ehco "Testing the code"
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploying step
        run: echo "Deploying"
