name: Hosting Static Website
on:
  push
jobs:
  staticWebsite:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: configure Aws Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Replace with your desired region
      - name: Run AWS CLI commands
        run: |
           echo "Current dir contents:"
           ls -la
           echo "Running sync command..."
           aws s3 sync ./ s3://githubactions-pratice/ --exclude "*" --include "index.html" --dryrun
           echo "Dryrun OK, now live sync..."
           aws s3 sync ./ s3://githubactions-pratice/ --exclude "*" --include "index.html" 
